#!/bin/sh
# Dbus system bus daemon for lksystem
rm -f /run/dbus/pid
mkdir -p /run/dbus /run/lksystem/started
touch /run/lksystem/started/dbus
dbus-uuidgen --ensure
# FIX: chpst -o strips stdout or stderr handles from dbus AND its children
exec chpst -o dbus-daemon --system --nofork --nopidfile
